### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by mwallace72** [shirshak55/edge-paths#4]
Looks like you had a preliminary Linux TODO: https://github.com/shirshak55/edge-paths/blob/master/linux_todo.txt as well as some scattered code in the `main.ts` file.

I believe Linux is now supported by Edge, and was wondering if you'd be updating this? Thanks!

**Comment by shirshak55** [comment]
@mwallace72 thanks for the notice :) I will be updating it soon .

**Comment by shirshak55** [comment]
Started to work on #6 if there are any concerns/issue please post it there for easier tracking.

Thank You.
